### ISSUE TITLE
AssertionError: Could not infer task type from

### ISSUE THREAD

**Issue by ParkJun-Yeong** [Hertin/WavPrompt#10]
![image](https://github.com/Hertin/WavPrompt/assets/71695015/ecad132d-00df-492a-97ca-f66ced08a0a6)

i ran "./run.sh" but i encountered this error.

```
Stage 10: Training Fairseq Model () (asr_pretraining)
Params: freeze_finetune_updates: 0 reduction_factor: 8 n_token: 0
2 previous hydra_train.log
/tmp/pycharm_project_frozen/WavPrompt/wavprompt/../fairseq/fairseq_cli/hydra_train.py:25: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_path=os.path.join("..", "fairseq", "config"), config_name="config")
/home/juny/miniconda3/envs/Frozen/lib/python3.10/site-packages/hydra/core/default_element.py:124: UserWarning: In 'asr_pretraining': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/changes_to_package_header for more information
  deprecation_warning(
sys:1: UserWarning: 
'asr_pretraining' is validated against ConfigStore schema with the same name.
This behavior is deprecated in Hydra 1.1 and will be removed in Hydra 1.2.
See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/automatic_schema_matching for migration instructions.
/home/juny/miniconda3/envs/Frozen/lib/python3.10/site-packages/hydra/main.py:94: UserWarning: 
'asr_pretraining' is validated against ConfigStore schema with the same name.
This behavior is deprecated in Hydra 1.1 and will be removed in Hydra 1.2.
See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/automatic_schema_matching for migration instructions.
  _run_hydra(
/home/juny/miniconda3/envs/Frozen/lib/python3.10/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  ret = run_job(
[2023-05-19 06:48:35,772][fairseq_cli.train][INFO] - {'_name': None, 'common': {'_name': None, 'no_progress_bar': False, 'log_interval': 200, 'log_format': 'json', 'log_file': None, 'aim_repo': None, 'aim_run_hash': None, 'tensorboard_logdir': None, 'wandb_project': None, 'azureml_logging': False, 'seed': 1, 'cpu': False, 'tpu': False, 'bf16': False, 'memory_efficient_bf16': False, 'fp16': True, 'memory_efficient_fp16': False, 'fp16_no_flatten_grads': False, 'fp16_init_scale': 128, 'fp16_scale_window': None, 'fp16_scale_tolerance': 0.0, 'on_cpu_convert_precision': False, 'min_loss_scale': 0.0001, 'threshold_loss_scale': None, 'amp': False, 'amp_batch_retries': 2, 'amp_init_scale': 128, 'amp_scale_window': None, 'user_dir': None, 'empty_cache_freq': 0, 'all_gather_list_size': 16384, 'model_parallel_size': 1, 'quantization_config_path': None, 'profile': False, 'reset_logging': False, 'suppress_crashes': False, 'use_plasma_view': False, 'plasma_path': '/tmp/plasma'}, 'common_eval': {'_name': None, 'path': None, 'post_process': None, 'quiet': False, 'model_overrides': '{}', 'results_path': None}, 'distributed_training': {'_name': None, 'distributed_world_size': 1, 'distributed_num_procs': 0, 'distributed_rank': 0, 'distributed_backend': 'nccl', 'distributed_init_method': None, 'distributed_port': -1, 'device_id': 0, 'distributed_no_spawn': False, 'ddp_backend': 'no_c10d', 'ddp_comm_hook': 'none', 'bucket_cap_mb': 25, 'fix_batches_to_gpus': False, 'find_unused_parameters': False, 'gradient_as_bucket_view': False, 'fast_stat_sync': False, 'heartbeat_timeout': -1, 'broadcast_buffers': False, 'slowmo_momentum': None, 'slowmo_base_algorithm': 'localsgd', 'localsgd_frequency': 3, 'nprocs_per_node': 1, 'pipeline_model_parallel': False, 'pipeline_balance': None, 'pipeline_devices': None, 'pipeline_chunks': 0, 'pipeline_encoder_balance': None, 'pipeline_encoder_devices': None, 'pipeline_decoder_balance': None, 'pipeline_decoder_devices': None, 'pipeline_checkpoint': 'never', 'zero_sharding': 'none', 'fp16': True, 'memory_efficient_fp16': False, 'tpu': False, 'no_reshard_after_forward': False, 'fp32_reduce_scatter': False, 'cpu_offload': False, 'use_sharded_state': False, 'not_fsdp_flatten_parameters': False}, 'dataset': {'_name': None, 'num_workers': 6, 'skip_invalid_size_inputs_valid_test': True, 'max_tokens': 1280000, 'batch_size': None, 'required_batch_size_multiple': 8, 'required_seq_len_multiple': 1, 'dataset_impl': None, 'data_buffer_size': 10, 'train_subset': 'train', 'valid_subset': 'dev', 'combine_valid_subsets': None, 'ignore_unused_valid_subsets': False, 'validate_interval': 1000, 'validate_interval_updates': 0, 'validate_after_updates': 1000, 'fixed_validation_seed': None, 'disable_validation': False, 'max_tokens_valid': 1280000, 'batch_size_valid': None, 'max_valid_steps': None, 'curriculum': 0, 'gen_subset': 'test', 'num_shards': 1, 'shard_id': 0, 'grouped_shuffling': False, 'update_epoch_batch_itr': False, 'update_ordered_indices_seed': False}, 'optimization': {'_name': None, 'max_epoch': 0, 'max_update': 100000, 'stop_time_hours': 0.0, 'clip_norm': 0.0, 'sentence_avg': True, 'update_freq': [10], 'lr': [0.0002], 'stop_min_lr': -1.0, 'use_bmuf': False, 'skip_remainder_batch': False}, 'checkpoint': {'_name': None, 'save_dir': '/mnt/hdd01_1tb/juny/frozentune_checkpoint', 'restore_file': 'checkpoint_last.pt', 'continue_once': None, 'finetune_from_model': None, 'reset_dataloader': False, 'reset_lr_scheduler': False, 'reset_meters': False, 'reset_optimizer': False, 'optimizer_overrides': '{}', 'save_interval': 1000, 'save_interval_updates': 500, 'keep_interval_updates': 1, 'keep_interval_updates_pattern': -1, 'keep_last_epochs': -1, 'keep_best_checkpoints': 1, 'no_save': False, 'no_epoch_checkpoints': True, 'no_last_checkpoints': False, 'no_save_optimizer_state': False, 'best_checkpoint_metric': 'loss', 'maximize_best_checkpoint_metric': False, 'patience': -1, 'checkpoint_suffix': '', 'checkpoint_shard_count': 1, 'load_checkpoint_on_all_dp_ranks': False, 'write_checkpoints_asynchronously': False, 'model_parallel_size': 1}, 'bmuf': {'_name': None, 'block_lr': 1.0, 'block_momentum': 0.875, 'global_sync_iter': 50, 'warmup_iterations': 500, 'use_nbm': False, 'average_sync': False, 'distributed_world_size': 1}, 'generation': {'_name': None, 'beam': 5, 'beam_mt': 0, 'nbest': 1, 'max_len_a': 0.0, 'max_len_b': 200, 'max_len_a_mt': 0.0, 'max_len_b_mt': 200, 'min_len': 1, 'match_source_len': False, 'unnormalized': False, 'no_early_stop': False, 'no_beamable_mm': False, 'lenpen': 1.0, 'lenpen_mt': 1.0, 'unkpen': 0.0, 'replace_unk': None, 'sacrebleu': False, 'score_reference': False, 'prefix_size': 0, 'no_repeat_ngram_size': 0, 'sampling': False, 'sampling_topk': -1, 'sampling_topp': -1.0, 'constraints': None, 'temperature': 1.0, 'diverse_beam_groups': -1, 'diverse_beam_strength': 0.5, 'diversity_rate': -1.0, 'print_alignment': None, 'print_step': False, 'lm_path': None, 'lm_weight': 0.0, 'iter_decode_eos_penalty': 0.0, 'iter_decode_max_iter': 10, 'iter_decode_force_max_iter': False, 'iter_decode_with_beam': 1, 'iter_decode_with_external_reranker': False, 'retain_iter_history': False, 'retain_dropout': False, 'retain_dropout_modules': None, 'decoding_format': None, 'no_seed_provided': False, 'eos_token': None}, 'eval_lm': {'_name': None, 'output_word_probs': False, 'output_word_stats': False, 'context_window': 0, 'softmax_batch': 9223372036854775807}, 'interactive': {'_name': None, 'buffer_size': 0, 'input': '-'}, 'model': {'_name': 'wavprompt', 'w2v_path': '/tmp/pycharm_project_frozen/WavPrompt/wavprompt/models/wav2vec_small.pt', 'apply_mask': True, 'mask_prob': 0.65, 'mask_channel_prob': 0.25, 'mask_channel_length': 64, 'layerdrop': 0.1, 'activation_dropout': 0.1, 'feature_grad_mult': 0.0, 'freeze_finetune_updates': 0, 'gpt_path': '/tmp/pycharm_project_frozen/WavPrompt/wavprompt/models/gpt2', 'gpt_type': 'gpt2', 'fix_encoder': False, 'fix_decoder': True, 'fix_conv_encoder': False, 'prompt': 'what did the speaker say? ', 'reduction_factor': 8, 'decoder_embed_dim': 768, 'n_token': 0, 'temp': '(2.0,0.5,0.999995)'}, 'task': {'_name': 'wavprompt_pretraining', 'data': '', 'normalize': False, 'labels': 'ltr', 'autoregressive': True, 'eval_wer': True, 'gpt_path': '/tmp/pycharm_project_frozen/WavPrompt/wavprompt/models/gpt2', 'debug': False, 'gpt_type': 'gpt2', 'max_sample_size': 320000}, 'criterion': {'_name': 'cross_entropy_with_acc'}, 'optimizer': {'_name': 'adam', 'adam_betas': '(0.9,0.98)', 'adam_eps': 1e-08, 'weight_decay': 0.0, 'use_old_adam': False, 'fp16_adam_stats': False, 'tpu': False, 'lr': [0.0002]}, 'lr_scheduler': {'_name': 'tri_stage', 'warmup_steps': 0, 'hold_steps': 0, 'decay_steps': 0, 'phase_ratio': [0.1, 0.4, 0.5], 'init_lr_scale': 0.01, 'final_lr_scale': 0.05, 'max_update': 100000.0, 'lr': [0.0002]}, 'scoring': None, 'bpe': None, 'tokenizer': None, 'ema': {'_name': None, 'store_ema': False, 'ema_decay': 0.9999, 'ema_start_update': 0, 'ema_seed_model': None, 'ema_update_freq': 1, 'ema_fp32': False}, 'job_logging_cfg': {'version': 1, 'formatters': {'simple': {'format': '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'}}, 'handlers': {'console': {'class': 'logging.StreamHandler', 'formatter': 'simple', 'stream': 'ext://sys.stdout'}, 'file': {'class': 'logging.FileHandler', 'formatter': 'simple', 'filename': '/mnt/hdd01_1tb/juny/frozentune_checkpoint/hydra_train.log'}}, 'root': {'level': 'INFO', 'handlers': ['console', 'file']}, 'disable_existing_loggers': False}}
Error executing job with overrides: ['task.data=', 'task.gpt_path=/tmp/pycharm_project_frozen/WavPrompt/wavprompt/models/gpt2', 'model.w2v_path=/tmp/pycharm_project_frozen/WavPrompt/wavprompt/models/wav2vec_small.pt', 'model.n_token=0', 'model.reduction_factor=8', 'model.gpt_path=/tmp/pycharm_project_frozen/WavPrompt/wavprompt/models/gpt2', 'model.freeze_finetune_updates=0', 'checkpoint.save_dir=/mnt/hdd01_1tb/juny/frozentune_checkpoint']
Traceback (most recent call last):
  File "/tmp/pycharm_project_frozen/WavPrompt/wavprompt/../fairseq/fairseq_cli/hydra_train.py", line 45, in hydra_main
    distributed_utils.call_main(cfg, pre_main)
  File "/home/juny/miniconda3/envs/Frozen/lib/python3.10/site-packages/fairseq/distributed/utils.py", line 369, in call_main
    main(cfg, **kwargs)
  File "/home/juny/miniconda3/envs/Frozen/lib/python3.10/site-packages/fairseq_cli/train.py", line 87, in main
    task = tasks.setup_task(cfg.task)
  File "/home/juny/miniconda3/envs/Frozen/lib/python3.10/site-packages/fairseq/tasks/__init__.py", line 43, in setup_task
    task is not None
AssertionError: Could not infer task type from {'_name': 'wavprompt_pretraining', 'data': '', 'normalize': False, 'labels': 'ltr', 'autoregressive': True, 'eval_wer': True, 'gpt_path': '/tmp/pycharm_project_frozen/WavPrompt/wavprompt/models/gpt2', 'debug': False, 'gpt_type': 'gpt2', 'max_sample_size': 320000}. Available argparse tasks: dict_keys(['translation', 'translation_from_pretrained_bart', 'language_modeling', 'masked_lm', 'speech_to_text', 'simul_speech_to_text', 'simul_text_to_text', 'audio_pretraining', 'audio_finetuning', 'nlu_finetuning', 'text_to_speech', 'speech_to_speech', 'denoising', 'speech_unit_modeling', 'hubert_pretraining', 'multilingual_translation', 'semisupervised_translation', 'multilingual_masked_lm', 'sentence_prediction', 'sentence_prediction_adapters', 'multilingual_language_modeling', 'frm_text_to_speech', 'multilingual_denoising', 'cross_lingual_lm', 'online_backtranslation', 'translation_lev', 'span_masked_lm', 'sentence_ranking', 'translation_from_pretrained_xlm', 'legacy_masked_lm', 'translation_multi_simple_epoch', 'dummy_lm', 'dummy_masked_lm', 'dummy_mt']). Available hydra tasks: dict_keys(['translation', 'language_modeling', 'masked_lm', 'simul_text_to_text', 'audio_pretraining', 'audio_finetuning', 'nlu_finetuning', 'denoising', 'speech_unit_modeling', 'hubert_pretraining', 'sentence_prediction', 'sentence_prediction_adapters', 'multilingual_language_modeling', 'multilingual_denoising', 'translation_lev', 'span_masked_lm', 'translation_from_pretrained_xlm', 'dummy_lm', 'dummy_masked_lm'])

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
(Frozen) juny@mlpa-a100:/tmp/pycharm_project_frozen/WavPrompt/wavprompt$ sudo bash ./run.sh
Stage 10: Training Fairseq Model () (asr_pretraining)
Params: freeze_finetune_updates: 0 reduction_factor: 8 n_token: 0
3 previous hydra_train.log
/tmp/pycharm_project_frozen/WavPrompt/wavprompt/../fairseq/fairseq_cli/hydra_train.py:25: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_path=os.path.join("..", "fairseq", "config"), config_name="config")
/home/juny/miniconda3/envs/Frozen/lib/python3.10/site-packages/hydra/core/default_element.py:124: UserWarning: In 'asr_pretraining': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/changes_to_package_header for more information
  deprecation_warning(
sys:1: UserWarning: 
'asr_pretraining' is validated against ConfigStore schema with the same name.
This behavior is deprecated in Hydra 1.1 and will be removed in Hydra 1.2.
See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/automatic_schema_matching for migration instructions.
/home/juny/miniconda3/envs/Frozen/lib/python3.10/site-packages/hydra/main.py:94: UserWarning: 
'asr_pretraining' is validated against ConfigStore schema with the same name.
This behavior is deprecated in Hydra 1.1 and will be removed in Hydra 1.2.
See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/automatic_schema_matching for migration instructions.
  _run_hydra(
/home/juny/miniconda3/envs/Frozen/lib/python3.10/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  ret = run_job(
[2023-05-19 06:58:02,156][fairseq_cli.train][INFO] - {'_name': None, 'common': {'_name': None, 'no_progress_bar': False, 'log_interval': 200, 'log_format': 'json', 'log_file': None, 'aim_repo': None, 'aim_run_hash': None, 'tensorboard_logdir': None, 'wandb_project': None, 'azureml_logging': False, 'seed': 1, 'cpu': False, 'tpu': False, 'bf16': False, 'memory_efficient_bf16': False, 'fp16': True, 'memory_efficient_fp16': False, 'fp16_no_flatten_grads': False, 'fp16_init_scale': 128, 'fp16_scale_window': None, 'fp16_scale_tolerance': 0.0, 'on_cpu_convert_precision': False, 'min_loss_scale': 0.0001, 'threshold_loss_scale': None, 'amp': False, 'amp_batch_retries': 2, 'amp_init_scale': 128, 'amp_scale_window': None, 'user_dir': None, 'empty_cache_freq': 0, 'all_gather_list_size': 16384, 'model_parallel_size': 1, 'quantization_config_path': None, 'profile': False, 'reset_logging': False, 'suppress_crashes': False, 'use_plasma_view': False, 'plasma_path': '/tmp/plasma'}, 'common_eval': {'_name': None, 'path': None, 'post_process': None, 'quiet': False, 'model_overrides': '{}', 'results_path': None}, 'distributed_training': {'_name': None, 'distributed_world_size': 1, 'distributed_num_procs': 0, 'distributed_rank': 0, 'distributed_backend': 'nccl', 'distributed_init_method': None, 'distributed_port': -1, 'device_id': 0, 'distributed_no_spawn': False, 'ddp_backend': 'no_c10d', 'ddp_comm_hook': 'none', 'bucket_cap_mb': 25, 'fix_batches_to_gpus': False, 'find_unused_parameters': False, 'gradient_as_bucket_view': False, 'fast_stat_sync': False, 'heartbeat_timeout': -1, 'broadcast_buffers': False, 'slowmo_momentum': None, 'slowmo_base_algorithm': 'localsgd', 'localsgd_frequency': 3, 'nprocs_per_node': 1, 'pipeline_model_parallel': False, 'pipeline_balance': None, 'pipeline_devices': None, 'pipeline_chunks': 0, 'pipeline_encoder_balance': None, 'pipeline_encoder_devices': None, 'pipeline_decoder_balance': None, 'pipeline_decoder_devices': None, 'pipeline_checkpoint': 'never', 'zero_sharding': 'none', 'fp16': True, 'memory_efficient_fp16': False, 'tpu': False, 'no_reshard_after_forward': False, 'fp32_reduce_scatter': False, 'cpu_offload': False, 'use_sharded_state': False, 'not_fsdp_flatten_parameters': False}, 'dataset': {'_name': None, 'num_workers': 6, 'skip_invalid_size_inputs_valid_test': True, 'max_tokens': 1280000, 'batch_size': None, 'required_batch_size_multiple': 8, 'required_seq_len_multiple': 1, 'dataset_impl': None, 'data_buffer_size': 10, 'train_subset': 'train', 'valid_subset': 'dev', 'combine_valid_subsets': None, 'ignore_unused_valid_subsets': False, 'validate_interval': 1000, 'validate_interval_updates': 0, 'validate_after_updates': 1000, 'fixed_validation_seed': None, 'disable_validation': False, 'max_tokens_valid': 1280000, 'batch_size_valid': None, 'max_valid_steps': None, 'curriculum': 0, 'gen_subset': 'test', 'num_shards': 1, 'shard_id': 0, 'grouped_shuffling': False, 'update_epoch_batch_itr': False, 'update_ordered_indices_seed': False}, 'optimization': {'_name': None, 'max_epoch': 0, 'max_update': 100000, 'stop_time_hours': 0.0, 'clip_norm': 0.0, 'sentence_avg': True, 'update_freq': [10], 'lr': [0.0002], 'stop_min_lr': -1.0, 'use_bmuf': False, 'skip_remainder_batch': False}, 'checkpoint': {'_name': None, 'save_dir': '/mnt/hdd01_1tb/juny/frozentune_checkpoint', 'restore_file': 'checkpoint_last.pt', 'continue_once': None, 'finetune_from_model': None, 'reset_dataloader': False, 'reset_lr_scheduler': False, 'reset_meters': False, 'reset_optimizer': False, 'optimizer_overrides': '{}', 'save_interval': 1000, 'save_interval_updates': 500, 'keep_interval_updates': 1, 'keep_interval_updates_pattern': -1, 'keep_last_epochs': -1, 'keep_best_checkpoints': 1, 'no_save': False, 'no_epoch_checkpoints': True, 'no_last_checkpoints': False, 'no_save_optimizer_state': False, 'best_checkpoint_metric': 'loss', 'maximize_best_checkpoint_metric': False, 'patience': -1, 'checkpoint_suffix': '', 'checkpoint_shard_count': 1, 'load_checkpoint_on_all_dp_ranks': False, 'write_checkpoints_asynchronously': False, 'model_parallel_size': 1}, 'bmuf': {'_name': None, 'block_lr': 1.0, 'block_momentum': 0.875, 'global_sync_iter': 50, 'warmup_iterations': 500, 'use_nbm': False, 'average_sync': False, 'distributed_world_size': 1}, 'generation': {'_name': None, 'beam': 5, 'beam_mt': 0, 'nbest': 1, 'max_len_a': 0.0, 'max_len_b': 200, 'max_len_a_mt': 0.0, 'max_len_b_mt': 200, 'min_len': 1, 'match_source_len': False, 'unnormalized': False, 'no_early_stop': False, 'no_beamable_mm': False, 'lenpen': 1.0, 'lenpen_mt': 1.0, 'unkpen': 0.0, 'replace_unk': None, 'sacrebleu': False, 'score_reference': False, 'prefix_size': 0, 'no_repeat_ngram_size': 0, 'sampling': False, 'sampling_topk': -1, 'sampling_topp': -1.0, 'constraints': None, 'temperature': 1.0, 'diverse_beam_groups': -1, 'diverse_beam_strength': 0.5, 'diversity_rate': -1.0, 'print_alignment': None, 'print_step': False, 'lm_path': None, 'lm_weight': 0.0, 'iter_decode_eos_penalty': 0.0, 'iter_decode_max_iter': 10, 'iter_decode_force_max_iter': False, 'iter_decode_with_beam': 1, 'iter_decode_with_external_reranker': False, 'retain_iter_history': False, 'retain_dropout': False, 'retain_dropout_modules': None, 'decoding_format': None, 'no_seed_provided': False, 'eos_token': None}, 'eval_lm': {'_name': None, 'output_word_probs': False, 'output_word_stats': False, 'context_window': 0, 'softmax_batch': 9223372036854775807}, 'interactive': {'_name': None, 'buffer_size': 0, 'input': '-'}, 'model': {'_name': 'wavprompt', 'w2v_path': '/tmp/pycharm_project_frozen/WavPrompt/wavprompt/models/wav2vec_small.pt', 'apply_mask': True, 'mask_prob': 0.65, 'mask_channel_prob': 0.25, 'mask_channel_length': 64, 'layerdrop': 0.1, 'activation_dropout': 0.1, 'feature_grad_mult': 0.0, 'freeze_finetune_updates': 0, 'gpt_path': '/tmp/pycharm_project_frozen/WavPrompt/wavprompt/models/gpt2', 'gpt_type': 'gpt2', 'fix_encoder': False, 'fix_decoder': True, 'fix_conv_encoder': False, 'prompt': 'what did the speaker say? ', 'reduction_factor': 8, 'decoder_embed_dim': 768, 'n_token': 0, 'temp': '(2.0,0.5,0.999995)'}, 'task': {'_name': 'wavprompt_pretraining', 'data': '', 'normalize': False, 'labels': 'ltr', 'autoregressive': True, 'eval_wer': True, 'gpt_path': '/tmp/pycharm_project_frozen/WavPrompt/wavprompt/models/gpt2', 'debug': False, 'gpt_type': 'gpt2', 'max_sample_size': 320000}, 'criterion': {'_name': 'cross_entropy_with_acc'}, 'optimizer': {'_name': 'adam', 'adam_betas': '(0.9,0.98)', 'adam_eps': 1e-08, 'weight_decay': 0.0, 'use_old_adam': False, 'fp16_adam_stats': False, 'tpu': False, 'lr': [0.0002]}, 'lr_scheduler': {'_name': 'tri_stage', 'warmup_steps': 0, 'hold_steps': 0, 'decay_steps': 0, 'phase_ratio': [0.1, 0.4, 0.5], 'init_lr_scale': 0.01, 'final_lr_scale': 0.05, 'max_update': 100000.0, 'lr': [0.0002]}, 'scoring': None, 'bpe': None, 'tokenizer': None, 'ema': {'_name': None, 'store_ema': False, 'ema_decay': 0.9999, 'ema_start_update': 0, 'ema_seed_model': None, 'ema_update_freq': 1, 'ema_fp32': False}, 'job_logging_cfg': {'version': 1, 'formatters': {'simple': {'format': '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'}}, 'handlers': {'console': {'class': 'logging.StreamHandler', 'formatter': 'simple', 'stream': 'ext://sys.stdout'}, 'file': {'class': 'logging.FileHandler', 'formatter': 'simple', 'filename': '/mnt/hdd01_1tb/juny/frozentune_checkpoint/hydra_train.log'}}, 'root': {'level': 'INFO', 'handlers': ['console', 'file']}, 'disable_existing_loggers': False}}
Error executing job with overrides: ['task.data=', 'task.gpt_path=/tmp/pycharm_project_frozen/WavPrompt/wavprompt/models/gpt2', 'model.w2v_path=/tmp/pycharm_project_frozen/WavPrompt/wavprompt/models/wav2vec_small.pt', 'model.n_token=0', 'model.reduction_factor=8', 'model.gpt_path=/tmp/pycharm_project_frozen/WavPrompt/wavprompt/models/gpt2', 'model.freeze_finetune_updates=0', 'checkpoint.save_dir=/mnt/hdd01_1tb/juny/frozentune_checkpoint']
Traceback (most recent call last):
  File "/tmp/pycharm_project_frozen/WavPrompt/wavprompt/../fairseq/fairseq_cli/hydra_train.py", line 45, in hydra_main
    distributed_utils.call_main(cfg, pre_main)
  File "/home/juny/miniconda3/envs/Frozen/lib/python3.10/site-packages/fairseq/distributed/utils.py", line 369, in call_main
    main(cfg, **kwargs)
  File "/home/juny/miniconda3/envs/Frozen/lib/python3.10/site-packages/fairseq_cli/train.py", line 87, in main
    task = tasks.setup_task(cfg.task)
  File "/home/juny/miniconda3/envs/Frozen/lib/python3.10/site-packages/fairseq/tasks/__init__.py", line 43, in setup_task
    task is not None


AssertionError: Could not infer task type from {'_name': 'wavprompt_pretraining', 'data': '', 'normalize': False, 'labels': 'ltr', 'autoregressive': True, 'eval_wer': True, 'gpt_path': '/tmp/pycharm_project_frozen/WavPrompt/wavprompt/models/gpt2', 'debug': False, 'gpt_type': 'gpt2', 'max_sample_size': 320000}. Available argparse tasks: dict_keys(['translation', 'translation_from_pretrained_bart', 'language_modeling', 'masked_lm', 'speech_to_text', 'simul_speech_to_text', 'simul_text_to_text', 'audio_pretraining', 'audio_finetuning', 'nlu_finetuning', 'text_to_speech', 'speech_to_speech', 'denoising', 'speech_unit_modeling', 'hubert_pretraining', 'multilingual_translation', 'semisupervised_translation', 'multilingual_masked_lm', 'sentence_prediction', 'sentence_prediction_adapters', 'multilingual_language_modeling', 'frm_text_to_speech', 'multilingual_denoising', 'cross_lingual_lm', 'online_backtranslation', 'translation_lev', 'span_masked_lm', 'sentence_ranking', 'translation_from_pretrained_xlm', 'legacy_masked_lm', 'translation_multi_simple_epoch', 'dummy_lm', 'dummy_masked_lm', 'dummy_mt']). Available hydra tasks: dict_keys(['translation', 'language_modeling', 'masked_lm', 'simul_text_to_text', 'audio_pretraining', 'audio_finetuning', 'nlu_finetuning', 'denoising', 'speech_unit_modeling', 'hubert_pretraining', 'sentence_prediction', 'sentence_prediction_adapters', 'multilingual_language_modeling', 'multilingual_denoising', 'translation_lev', 'span_masked_lm', 'translation_from_pretrained_xlm', 'dummy_lm', 'dummy_masked_lm'])

```

how can I do for pretraining it successfully?

**Comment by Hertin** [comment]
This mean fairseq does not have wavprompt_pretraining.py file in tasks. You might missed stage 2 in setup.sh

**Comment by ParkJun-Yeong** [comment]
I removed my miniconda, reseted the setting today and did every step one by one correctly.
then assertion error above has been solved. but new error occured.

![image](https://github.com/Hertin/WavPrompt/assets/71695015/c51643da-34f3-481a-ae2a-6ed3fb578521)

there are "examples" package and its __init__.py file in fairseq directory as u can see below.
![image](https://github.com/Hertin/WavPrompt/assets/71695015/fb44e62d-0f67-4797-b594-11d954da9473)

**Comment by Hertin** [comment]
This is a Python import issue. I don't know how to solve it. In previous issues, someone mentioned using "python setup.py build develop" can solve it. Maybe give it a try?
