### ISSUE TITLE
when i loading train data for epoch1.

### ISSUE THREAD

**Issue by guobabaya** [Hertin/WavPrompt#3]
[2022-05-18 20:16:17,321][fairseq_cli.train][INFO] - training on 1 devices (GPUs/TPUs)
[2022-05-18 20:16:17,322][fairseq_cli.train][INFO] - max tokens per device = 1280000 and max sentences per device = None
[2022-05-18 20:16:17,325][fairseq.trainer][INFO] - Preparing to load checkpoint /home/pengtl/WavPrompt/wavprompt/outputs/wavpromptlsp100rf8ntok0/checkpoint_last.pt
[2022-05-18 20:16:17,326][fairseq.trainer][INFO] - No existing checkpoint found /home/pengtl/WavPrompt/wavprompt/outputs/wavpromptlsp100rf8ntok0/checkpoint_last.pt
[2022-05-18 20:16:17,326][fairseq.trainer][INFO] - loading train data for epoch 1
[2022-05-18 20:16:17,339][fairseq.data.audio.raw_audio_dataset][INFO] - loaded 2703, skipped 0 samples
labels[0] [1169, 890, 1454, 26413, 550, 9258, 26735, 550, 2900, 510, 2927, 945, 290, 37191, 379, 262, 4220, 13, 50256]
[2022-05-18 20:16:19,222][fairseq.data.iterators][INFO] - grouped total_num_itrs = 31
[2022-05-18 20:16:19,246][fairseq.trainer][INFO] - begin training epoch 1
[2022-05-18 20:16:19,247][fairseq_cli.train][INFO] - Start iterating over samples
[2022-05-18 20:16:21,067][fairseq.trainer][INFO] - Saving checkpoint to /home/pengtl/WavPrompt/wavprompt/outputs/wavpromptlsp100rf8ntok0/crash.pt
[2022-05-18 20:16:25,254][fairseq.trainer][INFO] - Finished saving checkpoint to /home/pengtl/WavPrompt/wavprompt/outputs/wavpromptlsp100rf8ntok0/crash.pt
Traceback (most recent call last):
  File "/home/pengtl/WavPrompt/fairseq/fairseq_cli/hydra_train.py", line 27, in hydra_main
    _hydra_main(cfg)
  File "/home/pengtl/WavPrompt/fairseq/fairseq_cli/hydra_train.py", line 56, in _hydra_main
    distributed_utils.call_main(cfg, pre_main, **kwargs)
  File "/home/pengtl/WavPrompt/fairseq/fairseq/distributed/utils.py", line 369, in call_main
    main(cfg, **kwargs)
  File "/home/pengtl/WavPrompt/fairseq/fairseq_cli/train.py", line 190, in main
    valid_losses, should_stop = train(cfg, trainer, task, epoch_itr)
  File "/home/pengtl/anaconda3/envs/wavprompt/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/pengtl/WavPrompt/fairseq/fairseq_cli/train.py", line 316, in train
    log_output = trainer.train_step(samples)
  File "/home/pengtl/anaconda3/envs/wavprompt/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/pengtl/WavPrompt/fairseq/fairseq/trainer.py", line 830, in train_step
    **extra_kwargs,
  File "/home/pengtl/WavPrompt/fairseq/fairseq/tasks/fairseq_task.py", line 512, in train_step
    loss, sample_size, logging_output = criterion(model, sample)
  File "/home/pengtl/anaconda3/envs/wavprompt/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/pengtl/WavPrompt/fairseq/fairseq/criterions/cross_entropy_with_accuracy.py", line 34, in forward
    net_output = model(**sample["net_input"])
  File "/home/pengtl/anaconda3/envs/wavprompt/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/pengtl/WavPrompt/fairseq/fairseq/models/wavprompt/wavprompt.py", line 450, in forward
    encoder_out = self.encoder(tbc=False, **kwargs)
  File "/home/pengtl/anaconda3/envs/wavprompt/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/pengtl/WavPrompt/fairseq/fairseq/models/wavprompt/wavprompt.py", line 769, in forward
    x, padding_mask = self.extract_encoder_features(source, padding_mask)
  File "/home/pengtl/WavPrompt/fairseq/fairseq/models/wavprompt/wavprompt.py", line 734, in extract_encoder_features
    x, padding_mask = self.w2v_model.extract_features(**w2v_args)
ValueError: too many values to unpack (expected 2)

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by Hertin** [comment]
I do not have this problem on my machine. Did you check out the specific version of fairseq (1bba712622b8ae4efb3eb793a8a40da386fe11d0) as specified in setup.sh? They changed their wav2vec API a few times.

**Comment by guobabaya** [comment]
> I do not have this problem on my machine. Did you check out the specific version of fairseq (1bba712622b8ae4efb3eb793a8a40da386fe11d0) as specified in setup.sh? They changed their wav2vec API a few times.

Lab server can't pull using git, so didn't roll back to the specific version before, I'll try again, thank you.

**Comment by guobabaya** [comment]
> I do not have this problem on my machine. Did you check out the specific version of fairseq (1bba712622b8ae4efb3eb793a8a40da386fe11d0) as specified in setup.sh? They changed their wav2vec API a few times.

In this version of fairseq(1bba712622b8ae4efb3eb793a8a40da386fe11d0),wav2vec_manifest.py is damaged and cannot be used，can you check it.

**Comment by Hertin** [comment]
What do you mean by "damaged and cannot be used"? Do you have error message? wav2vec_manifest is fairseq code and is not maintained by me. You can access it from (https://github.com/facebookresearch/fairseq/blob/1bba712622b8ae4efb3eb793a8a40da386fe11d0/examples/wav2vec/wav2vec_manifest.py)

**Comment by guobabaya** [comment]
> What do you mean by "damaged and cannot be used"? Do you have error message? wav2vec_manifest is fairseq code and is not maintained by me. You can access it from (https://github.com/facebookresearch/fairseq/blob/1bba712622b8ae4efb3eb793a8a40da386fe11d0/examples/wav2vec/wav2vec_manifest.py)

Sorry, it's my misoperation that caused the file damage，thank you.
