### ISSUE TITLE
环境配置出错

### ISSUE THREAD

**Issue by guobabaya** [Hertin/WavPrompt#9]
高前辈你好，我又来打扰你了。我换了台电脑使用setup.sh重新配置环境以后运行一直报错，是使用了指定版本的fairseq，我重装了好多次还这样，我使用pip安装了example以后还是又会提示缺少其他module。

(wavprompt) [pengtl@vm-07 wavprompt]$ ./run.sh --stage 10 --stop-stage 10 --manifest-path "/home/pengtl/WavPrompt/wavprompt/manifest/10h-librispeech"  --config-name "asr_pretraining"   --n-token 0 --reduction-factor 8  --freeze_finetune_updates 0  --save-dir "/home/pengtl/WavPrompt/wavprompt/outputs/test1"
Stage 10: Training Fairseq Model (/home/pengtl/WavPrompt/wavprompt/manifest/10h-librispeech) (asr_pretraining)
Params: freeze_finetune_updates: 0 reduction_factor: 8 n_token: 0
Traceback (most recent call last):
  File "/data2/pengtl/WavPrompt/fairseq/fairseq_cli/hydra_train.py", line 11, in <module>
    from fairseq.dataclass.initialize import add_defaults, hydra_init
  File "/data2/pengtl/WavPrompt/fairseq/fairseq/__init__.py", line 32, in <module>
    import fairseq.criterions  # noqa
  File "/data2/pengtl/WavPrompt/fairseq/fairseq/criterions/__init__.py", line 36, in <module>
    importlib.import_module("fairseq.criterions." + file_name)
  File "/data2/pengtl/anaconda3/envs/wavprompt/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/data2/pengtl/WavPrompt/fairseq/fairseq/criterions/label_smoothed_cross_entropy_latency_augmented.py", line 6, in <module>
    from examples.simultaneous_translation.utils.latency import LatencyTraining
ModuleNotFoundError: No module named 'examples'

使用pip安装完examples后

(wavprompt) [pengtl@vm-07 wavprompt]$ ./run.sh --stage 10 --stop-stage 10 --manifest-path "/home/pengtl/WavPrompt/wavprompt/manifest/10h-librispeech"  --config-name "asr_pretraining"   --n-token 0 --reduction-factor 8  --freeze_finetune_updates 0  --save-dir "/home/pengtl/WavPrompt/wavprompt/outputs/test1"
Stage 10: Training Fairseq Model (/home/pengtl/WavPrompt/wavprompt/manifest/10h-librispeech) (asr_pretraining)
Params: freeze_finetune_updates: 0 reduction_factor: 8 n_token: 0
Traceback (most recent call last):
  File "/data2/pengtl/WavPrompt/fairseq/fairseq_cli/hydra_train.py", line 11, in <module>
    from fairseq.dataclass.initialize import add_defaults, hydra_init
  File "/data2/pengtl/WavPrompt/fairseq/fairseq/__init__.py", line 32, in <module>
    import fairseq.criterions  # noqa
  File "/data2/pengtl/WavPrompt/fairseq/fairseq/criterions/__init__.py", line 36, in <module>
    importlib.import_module("fairseq.criterions." + file_name)
  File "/data2/pengtl/anaconda3/envs/wavprompt/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/data2/pengtl/WavPrompt/fairseq/fairseq/criterions/label_smoothed_cross_entropy_latency_augmented.py", line 6, in <module>
    from examples.simultaneous_translation.utils.latency import LatencyTraining
ModuleNotFoundError: No module named 'examples.simultaneous_translation'

是我的环境配置哪个地方出错或者漏了什么东西吗，希望能得到您的一些建议，万分感谢！

**Comment by Hertin** [comment]
我不太清楚，你不应该装examples的，from  examples.simultaneous_translation.utils.latency 这个只是去fairseq/examples.simultaneous_translation/utils/latency.py 里找东西，不知道为什么你的fairseq没有能按照这个路径找
FAIRSEQ_ROOT这个变量你有设置对吗

**Comment by guobabaya** [comment]
> 我不太清楚，你不应该装examples的，from examples.simultaneous_translation.utils.latency 这个只是去fairseq/examples.simultaneous_translation/utils/latency.py 里找东西，不知道为什么你的fairseq没有能按照这个路径找 FAIRSEQ_ROOT这个变量你有设置对吗

谢谢你高前辈，已经解决啦。我运行了python setup.py build develop这句代码以后就可以了。
